### ISSUE TITLE
bot dont send the offer.

### ISSUE THREAD

**Issue by cezdemon** [pricempire/csgoempire-deposit-bot#37]
hi, i know the bot cant corfim the trade because SDA is outdated and im using your script to corfim the trades, but the bot dont even send the trade anymore. 
![image](https://github.com/pricempire/csgoempire-deposit-bot/assets/135801369/597747d8-faab-4935-8fd9-ba2d209c3d4e)

**Comment by easton36** [comment]
The `steamcommunity` package inside the bot needs to be updated to version 3.45.2

**Comment by cezdemon** [comment]
> The `steamcommunity` package inside the bot needs to be updated to version 3.45.2

how i do it?

**Comment by cezdemon** [comment]
how do i do it?

**Comment by easton36** [comment]
`npm update steamcommunity`

**Comment by cezdemon** [comment]
ty, iil see if it works

**Comment by cezdemon** [comment]
didnt fix my problem but thx anyway
